[scripts](devolo-apk): update d59881af5a
this is a update from https://codeberg.org/jschwart/devolo-extract-ghn-packages

diff --git a/scripts/devolo-extract-ghn-packages b/scripts/devolo-extract-ghn-packages
--- a/scripts/devolo-extract-ghn-packages
+++ b/scripts/devolo-extract-ghn-packages
@@ -60,6 +60,11 @@ do
         echo "Invalid destination: ${arg}" >&2
         exit 1
       fi
+      if [ -e ${dest_dir} -a ! -d ${dest_dir} ]
+      then
+        echo "Invalid destination: ${arg}" >&2
+        exit 1
+      fi
   esac
 done
 
@@ -178,6 +183,7 @@ patch_file()
       mv "${file_to_patch}" "${file_to_patch}.uClibc"
       echo "#!/bin/sh" > "${file_to_patch}"
       echo "export LD_LIBRARY_PATH=/lib-uClibc:/usr/lib-uClibc" >> "${file_to_patch}"
+      echo "test -L /var/run/ubus.sock || ln -s ubus/ubus.sock /var/run/ubus.sock" >> "${file_to_patch}"
       echo "$(basename ${file_to_patch}).uClibc \"\$@\"" >> "${file_to_patch}"
       chmod +x "${file_to_patch}"
     ;;
@@ -357,7 +363,7 @@ pushd "${tmp_dir}"
 binwalk --extract "${firmware}"
 root_dir=$(realpath ${tmp_dir}/*/squashfs-root)
 
-for package in ${root_dir}/usr/lib/opkg/info/{delos-base-files,delos-device-name,devolo-shared-configlayer,dlan2-fw-flashless-*,dlan2-tools,ghn-flashless,ghn-host,libssp,posix-timezone-db}.list
+for package in ${root_dir}/usr/lib/opkg/info/{delos-base-files,delos-device-name,devolo-shared-configlayer,dlan2-fw-flashless-*,dlan2-tools,ghn-flashless,ghn-host,libssp,posix-timezone-db,delos-rpcd-ghntool}.list
 do
   build_package_for_opkg_data ${package::-5} "${dest_dir}"
 done
